class Globals {
  static final String latitudeKey = 'latitudeKey';
  static final String longitudeKey = 'longitudeKey';
  static final String gpsModeKey = 'gpsModeKey';
  static final String formattedLocationKey = 'formattedLocationKey';

  static final Map<String, String> constellationDescriptions = {
    'And': 'Daughter of Cassiopeia',
    'Ant': 'Air Pump',
    'Aps': 'Bird of Paradise',
    'Aqr': 'Water Bearer',
    'Aql': 'Eagle',
    'Ara': 'Altar',
    'Ari': 'Ram',
    'Aur': 'Charioteer',
    'Boo': 'Herdsman',
    'Cae': 'Chisel',
    'Cam': 'Giraffe',
    'Cnc': 'Crab',
    'CVn': 'Hunting Dogs',
    'CMa': 'Greater Dog',
    'CMi': 'Minor Dog',
    'Cap': 'Horned Goat',
    'Car': 'Ship Hull',
    'Cas': 'Mother of Andromeda',
    'Cen': 'Centaur',
    'Cep': 'King of Aethiopia',
    'Cet': 'Whale',
    'Cha': 'Chameleon',
    'Cir': 'Drawing Compass',
    'Col': 'Dove',
    'Com': 'Queen Berenice\'s Hair',
    'CrA': 'Southern Crown',
    'CrB': 'Northern Crown',
    'Crv': 'Crow',
    'Crt': 'Cup',
    'Cru': 'Southern Cross',
    'Cyg': 'Northern Cross',
    'Del': 'Dolphin',
    'Dor': 'Swordfish',
    'Dra': 'Dragon',
    'Equ': 'Pony',
    'Eri': 'River',
    'For': 'Furnace',
    'Gem': 'Twins',
    'Gru': 'Crane',
    'Her': 'Hercules',
    'Hor': 'Pendulum Clock',
    'Hya': 'Female Water Snake',
    'Hyi': 'Male Water Snake',
    'Ind': 'Indian',
    'Lac': 'Lizard',
    'Leo': 'Lion',
    'LMi': 'Lesser Lion',
    'Lep': 'Hare',
    'Lib': 'Weighing Scales',
    'Lup': 'Wolf',
    'Lyn': 'Lynx',
    'Lyr': 'Lyre',
    'Men': 'Table Mountain',
    'Mic': 'Microscope',
    'Mon': 'Unicorn',
    'Mus': 'Fly',
    'Nor': 'Carpenter\'s Square',
    'Oct': 'Reflecting Quadrant',
    'Oph': 'Serpent Bearer',
    'Ori': 'Orion the Hunter',
    'Pav': 'Peacock',
    'Peg': 'Pegasus the Winged Horse',
    'Per': 'Son of Zeus',
    'Phe': 'Phoenix',
    'Pic': 'Easel',
    'Psc': 'Fishes',
    'PsA': 'Southern Fish',
    'Pup': 'Poop Deck',
    'Pyx': 'Mariner\'s Compass',
    'Ret': 'Reticle',
    'Sge': 'Arrow',
    'Sgr': 'Archer',
    'Sco': 'Scorpion',
    'Scl': 'Sculptor',
    'Sct': 'Shield',
    'Ser': 'Snake',
    'Sex': 'Sextant',
    'Tau': 'Bull',
    'Tel': 'Telescope',
    'Tri': 'Triangle',
    'TrA': 'Southern Triangle',
    'Tuc': 'Toucan',
    'UMa': 'Great Bear',
    'UMi': 'Little Bear',
    'Vel': 'Ship Sails',
    'Vir': 'Virgin',
    'Vol': 'Flying Fish',
    'Vul': 'Fox',
  };
}
